{% set name = "django-contrib-comments" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48de00f15677e016a216aeff205d6e00e4391c9a5702136c64119c472b7356da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4
    - pip
  run:
    - python >=3.7,<4
    - django >=3.2

test:
  imports:
    - django_comments
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://django-contrib-comments.readthedocs.io/
  summary: 'The official Django comments framework'
  description: |
    Django used to include a comments framework; since Django 1.6 
    it’s been separated to a separate project. This is that project.
    This framework can be used to attach comments to any model, so you 
    can use it for comments on blog entries, photos, book chapters, 
    or anything else.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://django-contrib-comments.readthedocs.io/
  dev_url: https://github.com/django/django-contrib-comments/

extra:
  recipe-maintainers:
    - jacksund
